version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    links:
    - zookeeper:zookeeper
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
